### PR TITLE
parse MAX_ENTRIES and CULL_FREQUENCY

### PR DESCRIPTION
**Pull request by satyrius**
Parse cache arguments to configure OPTIONS https://docs.djangoproject.com/en/1.10/topics/cache/#cache-arguments

### CODE REVIEW

**Comment by ghickman** [comment]
@satyrius – thanks for these changes.  Do you have any more coming in today?  I'll hold off releasing if so.

**Comment by satyrius** [comment]
Thats it for today. Just want to be able to setup `MAX_ENTRIES`. It will be great if you will do minor release. Thank you.

**Comment by ghickman** [comment]
v1.2.0 is now [on the PyPI](https://pypi.python.org/pypi/django-cache-url)

**Comment by satyrius** [comment]
Thank you!

**Pull request merged**
