### PR TITLE
Adds support for django-redis version >=3.8.0 unix:// locations

### PR DESCRIPTION
**Pull request by alanjds**
Made over #31. Please ask if needed a pure one over ``master``. Should be a 8-line patch starting on ``unix_db_separator``.

### CODE REVIEW

**Comment by m1kola** [comment]
Hi @alanjds and @ghickman,

Please, let me know, if you need any help with this PR.

Wold be great to finally fix this issue, because [the change log](https://github.com/ghickman/django-cache-url/blob/ec31d4b54433a21807971284e970fe5e0fa118a7/CHANGELOG.rst) says that `django-cache-url` supports `django-redis>=4.5.0` and the readme says that I can use socket urls like `redis:///PATH/TO/SOCKET[/DB]`. But socket urls do not work with `django-redis >= 4.5.0`.

**Comment by alanjds** [comment]
@m1kola Eh... sorry but it is a bit of time from when I coded this. It worked at that time but I am not actively using it on any project for now.

**Comment by alanjds** [comment]
Hum... the django-redis docs at 4.8.0 says it do supports unix sockets: http://niwinz.github.io/django-redis/latest/#_configure_as_cache_backend 

So, it should work out of the box, right?

**Comment by alanjds** [comment]
Anyway, I really would like #31 to be merged. The tests are failing because of pypy3 only :/

**Comment by ghickman** [comment]
Closing for the same reason as #33

**Pull request closed without merging**
