### PR TITLE
support for new LOCATION url syntax in django-redis >= 3.8.0

### PR DESCRIPTION
**Pull request by slafs**
I've added some new schemes and unified the syntax for UNIX based URLs as well as the standard HOST:PORT ones. I tried to do this as much unobtrusive as I could.

### CODE REVIEW

**Comment by slafs** [comment]
Oh, this also adds support for the new path for the backend (``django_redis.cache.RedisCache``).

I noticed that Travis reported errors for python 2.6. I looked into it and It seems that python2.6 urlparse handles path and query differently than in other versions. Don't know exactly how to address this and also avoid bloat... Maybe some compat module would be suitable here?

**Comment by ghickman** [comment]
@slafs – thanks for taking the time to raise these changes.

Are the new schemes (`djredis`, `djrediss`, `djhiredis`, `djhirediss`, `djredisunix`, `djhiredisunix`) what django-redis >= 3.8.0 adds? Could you point me at a documentation link if you have one?

As for the unified syntax for UNIX urls could you take that out of your patch please? It's very hard for me to pull apart the difference between those changes and the scheme ones and a PR should only introduce one change.

I'm hoping to roll a 1.0 release very soon and would love to have the updated scheme changes in that if possible. I'll also be rolling in #17 so it would be great if you could base your changes off those too (they're pushed in the 1.0-release branch) which will sort out the python 2.6 urlparse issue you saw.

**Comment by slafs** [comment]
Hey! 
Docs for the new syntax are [here](http://niwinz.github.io/django-redis/latest/#_configure_as_cache_backend).

As for the UNIX case I guess I just wanted to show that there's no need to do hackery things like in the current implementation and those URLs can be easily handled the same way as the rest of cases. So maybe we can keep this here?

Will try to make my changes on top of #17.

**Comment by ghickman** [comment]
@slafs – thanks for the docs link!

I've been doing all the 1.0 work in the `1.0-release` branch today so if you check that out it's got #17 as the base with a bunch of other changes on top.

**Comment by ghickman** [comment]
@slafs – thanks for all your contributions to the project but I've decided to deprecate in favour of [Django Environ](https://pypi.org/project/django-environ/).

**Pull request closed without merging**
